# Evaluate

In [1]:
import pandas as pd
import sys
sys.path += ["../../.."]
from utils import is_valid_aa_change_in_experiment_id, is_valid_aa_change_mutation
from src.benchmark.benchmark_utils import get_mutation_corrected
import numpy as np

# Reflect changes in the modules immediately.
%load_ext autoreload
%autoreload 2

In [35]:
predictions = pd.read_csv("kim_prediction_2021-11-19/c137c19d/predictions_soft_2021-11-19.csv")
predictions.head()

  UniProt_ID Mutation Interactor_UniProt_ID  Prediction  Median_Probability
0     O96017    K373E                O43293           1             0.52331
1     O96017    K373E                O15297           1             0.70992
2     P01112     G12D                Q12967           1             0.58402
3     P01112     G12D                O95267           1             0.59477
4     P01112     G12D                Q8TDF6           1             0.60715

# Supp 03

In [4]:
supp3_sheet1 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S3.xlsx", sheet_name=1)
supp3_sheet2 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S3.xlsx", sheet_name=2)
supp3_sheet3 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S3.xlsx", sheet_name=3)

In [5]:
def parse_supp3_sheet_1(data):
    # Parse sheet 1
    data_parsed = data[
        data["Experiment.ID"].apply(lambda x: is_valid_aa_change_in_experiment_id(x))
    ].copy()
    data_parsed = data_parsed[
        ~data_parsed["FoldChange"].isna()
    ]
    data_parsed["PROTEIN"] = data_parsed["Bait ID"]
    data_parsed["MUTATION"] = data_parsed["Experiment.ID"].apply(
        lambda x: get_mutation_corrected(x.split('_')[1])
    )
    data_parsed["INTERACTOR"] = data_parsed["Prey ID"]
    data_parsed["MUTATION_EFFECT"] = data_parsed["FoldChange"].apply(lambda x: int(np.log2(x) > 0))
    data_ready = data_parsed[["PROTEIN", "MUTATION", "INTERACTOR", "MUTATION_EFFECT"]].copy()
    return data_ready

def parse_supp3_sheet_2(data):
    return parse_supp3_sheet_1(data)

def parse_supp3_sheet_3(data):
    data = data[
        ~data["Experiment.ID"].isna()
    ].copy()
    return parse_supp3_sheet_1(data)

In [6]:
# Parse sheet 1
supp3_sheet1_ready = parse_supp3_sheet_1(supp3_sheet1)

In [7]:
# Parse sheet 2
supp3_sheet2_ready = parse_supp3_sheet_2(supp3_sheet2)

In [8]:
# Parse sheet 3
supp3_sheet3_ready = parse_supp3_sheet_3(supp3_sheet3)

In [9]:
# Merge all sheets in supp 03
supp3_merged = pd.concat([
    supp3_sheet1_ready, supp3_sheet2_ready, supp3_sheet3_ready
])
supp3_merged = supp3_merged.drop_duplicates()
supp3_merged.reset_index(drop=True, inplace=True)
supp3_merged.head()

  PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
0  P31749     E17K     Q14532                1
1  P31749     E17K     Q16543                1
2  P31749     E17K     P33764                1
3  P31749     E17K     Q8IUC1                1
4  P31749     E17K     Q8WTT2                1

# Supp 04

In [10]:
supp4_sheet1 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S4.xlsx", sheet_name=1)
supp4_sheet2 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S4.xlsx", sheet_name=2)
supp4_sheet3 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S4.xlsx", sheet_name=3)
supp4_sheet4 = pd.read_excel("science.abf3066_tables_s2_to_s12/science.abf3066_Table_S4.xlsx", sheet_name=4)

In [27]:
def parse_supp4_sheet_1(data):
    # Parse sheet 1
    data_parsed = data[
        data["Experiment.ID"].apply(lambda x: is_valid_aa_change_in_experiment_id(x))
    ].copy()
    data_parsed = data_parsed[
        ~data_parsed["FoldChange"].isna()
    ]
    data_parsed["PROTEIN"] = data_parsed["Bait ID"]
    data_parsed["MUTATION"] = data_parsed["Experiment.ID"].apply(
        lambda x: get_mutation_corrected(x.split('_')[1])
    )
    data_parsed["INTERACTOR"] = data_parsed["Prey ID"]
    data_parsed["MUTATION_EFFECT"] = data_parsed["FoldChange"].apply(lambda x: int(np.log2(x) > 0))
    data_ready = data_parsed[["PROTEIN", "MUTATION", "INTERACTOR", "MUTATION_EFFECT"]].copy()
    return data_ready

def parse_supp4_sheet_2(data):
    # Parse sheet 2
    data_parsed = data[
        data["Experiment.ID"].apply(lambda x: is_valid_aa_change_mutation(x))
    ].copy()
    data_parsed = data_parsed[
        ~data_parsed["FoldChange"].isna()
    ]
    data_parsed["PROTEIN"] = data_parsed["Bait ID"]
    data_parsed["MUTATION"] = data_parsed["Experiment.ID"]
    data_parsed["INTERACTOR"] = data_parsed["Prey ID"]
    data_parsed["MUTATION_EFFECT"] = data_parsed["FoldChange"].apply(lambda x: int(np.log2(x) > 0))
    data_ready = data_parsed[["PROTEIN", "MUTATION", "INTERACTOR", "MUTATION_EFFECT"]].copy()
    return data_ready

def parse_supp4_sheet_3(data):
    return parse_supp4_sheet_1(data)

def parse_supp4_sheet_4(data):
    return parse_supp4_sheet_1(data)

In [16]:
# Parse sheet 1
supp4_sheet1_ready = parse_supp4_sheet_1(supp4_sheet1)

In [17]:
# Parse sheet 2
supp4_sheet2_ready = parse_supp4_sheet_2(supp4_sheet2)

In [23]:
# Parse sheet 3
supp4_sheet3_ready = parse_supp4_sheet_3(supp4_sheet3)

In [28]:
# Parse sheet 4
supp4_sheet4_ready = parse_supp4_sheet_4(supp4_sheet4)

In [29]:
supp4_sheet1_ready.head(3)

  PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
0  P31749     E17K     P33764                1
1  P31749     E17K     Q14532                1
2  P31749     E17K     Q16543                1

In [30]:
supp4_sheet2_ready.head(3)

   PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
39  P38398     C61G     Q9BX63                1
40  P38398     C61G     P40692                1
41  P38398     C61G     Q96RL1                1

In [31]:
supp4_sheet3_ready.head(3)

   PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
19  P12830    E243K     P35222                1
20  P12830    E243K     O60716                1
57  P01112     G12D     P13995                1

In [32]:
supp4_sheet4_ready.head(3)

   PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
0   P31749     E17K     P11717                1
21  P12830    E243K     P35222                1
22  P12830    E243K     P35221                1

In [25]:
supp4_sheet4

,Experiment.ID,Bait,Bait ID,Prey,Prey ID,Npat,AvePSM,Z,WD,Entropy,...,logOddsScore,FoldChange,BFDR,PPI Score,Uniprot-interaction,Comparison to IMEx,Comparison to BioPlex2,Comparison to BioGRID,Comparison to CORUM,All public DB novelty
0,AKT1_e17k,AKT1,P31749,IGF2R,P11717,8.0,4.333333,4.458938,0.178883,1.553763,...,-2.48,12.13,0.04,0.9315,P31749_P11717,Novel,Novel,Novel,Novel,Novel
1,AKT1_wt,AKT1,P31749,CSTB,P04080,NaN,2.666667,4.800000,27.726018,1.566367,...,-1.83,26.67,0.08,0.9590,P31749_P04080,Novel,Novel,Novel,Novel,Novel
2,AKT1_wt,AKT1,P31749,SPRR3,Q9UBC9,NaN,2.666667,4.800000,7.014189,1.566367,...,-1.83,26.67,0.08,0.9580,P31749_Q9UBC9,Novel,Novel,Novel,Novel,Novel
3,AKT1_wt,AKT1,P31749,CRNN,Q9UBG3,5.0,10.000000,4.800000,5.624506,1.554433,...,8.26,96.67,0.00,0.9980,P31749_Q9UBG3,Novel,Novel,Novel,Novel,Novel
4,AKT2_wt,AKT2,P31751,DSTN,P60981,NaN,5.000000,4.191027,0.417497,1.567955,...,-0.88,14.08,0.07,0.9470,P31751_P60981,Novel,Novel,Novel,Novel,Novel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,XPC,XPC,Q01831,CETN3,O15182,1.0,4.333333,3.396831,37.645373,1.534326,...,-4.16,23.33,0.19,0.9045,Q01831_O15182,Novel,Novel,Novel,Novel,Novel
97,XPC,XPC,Q01831,RAD23A,P54725,2.0,2.666667,2.778523,30.127659,1.566367,...,-2.13,26.67,0.11,0.9445,Q01831_P54725,Novel,Novel,Reported,Novel,Reported
98,XPC,XPC,Q01831,RAD23B,P54727,4.0,8.666667,3.540960,13.485923,1.577222,...,6.38,80.00,0.00,0.9985,Q01831_P54727,Reported,Novel,Reported,Novel,Reported
99,XRN2,XRN2,Q9H0D6,NKRF,O15226,4.0,5.000000,2.814074,8.380312,1.567955,...,1.76,50.00,0.00,0.9985,Q9H0D6_O15226,Novel,Novel,Novel,Novel,Novel
100,XRN2,XRN2,Q9H0D6,CDKN2AIP,Q9NXV6,3.0,2.666667,1.878837,10.409122,1.517529,...,-1.83,26.67,0.11,0.9435,Q9H0D6_Q9NXV6,Novel,Novel,Novel,Novel,Novel

In [26]:
supp4_sheet4["Experiment.ID"].unique()

array(['AKT1_e17k', 'AKT1_wt', 'AKT2_wt', 'AKT3_wt', 'ARID1A', 'BRIP1_wt',
       'CCND3', 'CDH1_e243k', 'CDH1_wt', 'CHEK2_1100delC', 'CTCF', 'EGFR',
       'ERBB2', 'EZH2', 'GATA3', 'HRAS_g12d', 'MSH2', 'MTDH_a78s',
       'MTDH_wt', 'PIK3CA_e545k', 'PIK3CA_wt', 'RB1', 'RPA2', 'SMARCB1',
       'SMARCD1', 'STK11', 'TBX3', 'TP53_r175h', 'TP53_wt', 'XPC', 'XRN2'],
      dtype=object)

In [9]:
# Parse sheet 1
supp3_sheet1_ready = parse_supp3_sheet_1(supp3_sheet1)

In [10]:
# Parse sheet 2
supp3_sheet2_ready = parse_supp3_sheet_2(supp3_sheet2)

In [11]:
# Parse sheet 3
supp3_sheet3_ready = parse_supp3_sheet_3(supp3_sheet3)

In [12]:
# Merge all sheets in supp 03
supp3_merged = pd.concat([
    supp3_sheet1_ready, supp3_sheet2_ready, supp3_sheet3_ready
])
supp3_merged = supp3_merged.drop_duplicates()
supp3_merged.reset_index(drop=True, inplace=True)
supp3_merged.head()

  PROTEIN MUTATION INTERACTOR  MUTATION_EFFECT
0  P31749     E17K     Q14532                1
1  P31749     E17K     Q16543                1
2  P31749     E17K     P33764                1
3  P31749     E17K     Q8IUC1                1
4  P31749     E17K     Q8WTT2                1

## Find Overlapping Triplets

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
prediction_triplets = set(
    zip(
        predictions["UniProt_ID"], predictions["Mutation"], predictions["Interactor_UniProt_ID"]
    )
)
print(len(prediction_triplets))

45

In [38]:
kim_supp03_triplets = set(
    zip(
        supp3_merged["PROTEIN"], supp3_merged["MUTATION"], supp3_merged["INTERACTOR"]
    )
)
print(len(kim_supp03_triplets))

48485

In [39]:
overlapping_triplets = prediction_triplets.intersection(kim_supp03_triplets)
overlapping_triplets

{('O96017', 'K373E', 'O43293'),
 ('P01112', 'G12D', 'Q13671'),
 ('P04637', 'R248W', 'P62993'),
 ('P04637', 'R273H', 'P62993'),
 ('P12830', 'E243K', 'P22223'),
 ('P42336', 'H1047R', 'O00459'),
 ('P42336', 'H1047R', 'P27986')}

In [40]:
def get_prediction(data, protein, mutation, interactor):
    query = data[
        (data["UniProt_ID"] == protein) &
        (data["Mutation"] == mutation) &
        (data["Interactor_UniProt_ID"] == interactor)
    ]
    [prediction] = query["Prediction"]
    return prediction

In [41]:
def get_observation(data, protein, mutation, interactor):
    query = data[
        (data["PROTEIN"] == protein) &
        (data["MUTATION"] == mutation) &
        (data["INTERACTOR"] == interactor)
    ]
    [observation] = query["MUTATION_EFFECT"]
    return observation

In [42]:
evaluation_data_entries = []
for triplet in overlapping_triplets:
    prot, mut, inter = triplet
    pred = get_prediction(predictions, prot, mut, inter)
    actual = get_observation(supp3_merged, prot, mut, inter)
    evaluation_data_entries.append(
        (prot, mut, inter, pred, actual)
    )

In [43]:
evaluation_data = pd.DataFrame(
    evaluation_data_entries, columns=["PROTEIN", "MUTATION", "INTERACTOR", "PREDICTION", "ACTUAL"]
)
evaluation_data

  PROTEIN MUTATION INTERACTOR  PREDICTION  ACTUAL
0  P04637    R248W     P62993           0       1
1  P04637    R273H     P62993           0       1
2  P12830    E243K     P22223           1       0
3  P01112     G12D     Q13671           1       1
4  P42336   H1047R     P27986           0       1
5  P42336   H1047R     O00459           0       1
6  O96017    K373E     O43293           1       1

In [44]:
accuracy_score(evaluation_data["ACTUAL"], evaluation_data["PREDICTION"])

0.2857142857142857

In [ ]:
## remained here--- find overlapping triplets and assess teh performance of predictions.